### ISSUE TITLE
Crash on report spam for 2 status

### ISSUE THREAD

**Issue by BlythMeister** [chrislacy/TweetLanes#414]
<a href="https://app.crittercism.com/developers/crash-details/ec93abb4ada8f556c16ecb2e82ade3664401372bd5c436bfc0723bf5"> View Crash Report on Crittercism </a> 

 Reported by: Chris Blyth (blythmeister@gmail.com)

Status: Unresolved

This Crash occured 1 times for 1 users

0 java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
1   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
2   at java.util.ArrayList.remove(ArrayList.java:399)
3   at org.tweetalib.android.model.TwitterStatuses.remove(TwitterStatuses.java:497)
4   at org.tweetalib.android.model.TwitterStatuses.remove(TwitterStatuses.java:406)
5   at org.tweetalib.android.fetch.TwitterFetchStatuses.removeFromHashMap(TwitterFetchStatuses.java:228)
6   at org.socialnetlib.android.SocialNetApi.removeFromHashMap(SocialNetApi.java:483)
7   at org.tweetalib.android.TwitterManager.removeFromHashMap(TwitterManager.java:158)
8   at com.tweetlanes.android.core.view.TweetFeedFragment$MultipleTweetSelectionCallback.onActionItemClicked(TweetFeedFragment.java:1685)
9   at android.widget.AbsListView$MultiChoiceModeWrapper.onActionItemClicked(AbsListView.java:6326)
10  at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onActionItemClicked(PhoneWindow.java:2724)
11  at com.android.internal.app.ActionBarImpl$ActionModeImpl.onMenuItemSelected(ActionBarImpl.java:931)
12  at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
13  at com.android.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:81)
14  at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
15  at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
16  at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:308)
17  at android.widget.AdapterView.performItemClick(AdapterView.java:298)
18  at android.widget.AbsListView.performItemClick(AbsListView.java:1150)
19  at android.widget.ListView.performItemClick(ListView.java:4397)
20  at android.widget.AbsListView$PerformClick.run(AbsListView.java:2985)
21  at android.widget.AbsListView$1.run(AbsListView.java:3671)
22  at android.os.Handler.handleCallback(Handler.java:615)
23  at android.os.Handler.dispatchMessage(Handler.java:92)
24  at android.os.Looper.loop(Looper.java:155)
25  at android.app.ActivityThread.main(ActivityThread.java:5454)
26  at java.lang.reflect.Method.invokeNative(Native Method)
27  at java.lang.reflect.Method.invoke(Method.java:511)
28  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
29  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
30  at dalvik.system.NativeStart.main(Native Method)

**Comment by BlythMeister** [comment]
Legacy issue, closing
