### ISSUE TITLE
Status Cache "java.lang.OutOfMemoryError"

### ISSUE THREAD

**Issue by BlythMeister** [chrislacy/TweetLanes#416]
<a href="https://app.crittercism.com/developers/crash-details/e04a34f698379b64689554ece1e24497d2cd6d3eefdd7667a6f0e532"> View Crash Report on Crittercism </a> 

 Reported by: Chris Blyth (blythmeister@gmail.com)

Status: Unresolved

This Crash occured 1 times for 1 users

0 java.lang.OutOfMemoryError: (Heap Size=64967KB, Allocated=54712KB)
1   at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
2   at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:132)
3   at java.lang.StringBuilder.append(StringBuilder.java:124)
4   at org.json.JSONStringer.string(JSONStringer.java:344)
5   at org.json.JSONStringer.value(JSONStringer.java:252)
6   at org.json.JSONArray.writeTo(JSONArray.java:572)
7   at org.json.JSONStringer.value(JSONStringer.java:233)
8   at org.json.JSONObject.writeTo(JSONObject.java:667)
9   at org.json.JSONObject.toString(JSONObject.java:636)
10  at com.tweetlanes.android.core.view.TweetFeedFragment.getDataToCache(TweetFeedFragment.java:547)
11  at com.tweetlanes.android.core.view.HomeActivity$4.run(HomeActivity.java:465)
12  at java.lang.Thread.run(Thread.java:864)

**Comment by BlythMeister** [comment]
Legacy issue, closing
